### PR TITLE
Added 'assert text' command

### PR DESCRIPTION
**Pull request by rsp9u**
These commits added `Assert Text` command.

@yaamai Remove `FIXME` comment on `execute_verify_text()` since it has been implemented.

### CODE REVIEW

**Comment by rsp9u** [comment]
@yaamai
BTW, this is a proposal, what do you say adding a something flag into result when `Verify Text` is failed? By this, we would be able to test that the text is excluded.

**Comment by rsp9u** [comment]
@yaamai
And I added an wiki page. Please use it if you prefer.
https://github.com/side-runner-py/side-runner-py/wiki/Useful-vim-scripts

**Comment by yaamai** [comment]
@rsp9u 

> @yaamai
> BTW, this is a proposal, what do you say adding a something flag into result when `Verify Text` is failed? By this, we would be able to test that the text is excluded.

like below?
```
output:
  - tests:
    - commands:
      - command: verifyText
        isFailedVerify: true
```

**Review by yaamai — APPROVED** [review]
lgtm

**Pull request merged**
